#!/usr/bin/env bash

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/rices/$RICETHEME/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

## You can edit this.
BSPWM_BORDER='1'
BSPWM_GAP='15'

function launch() {
  local running
  running="$(pgrep -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ResetTermite() {
  if [[ `pidof termite` ]]; then 
		killall -USR1 termite
  fi
}

function ReloadTermite() {
  if [ -f "$HOME/.config/termite/config" ]; then
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  else
		mkdir -p $HOME/.config/termite/ && touch $HOME/.config/termite/config
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  fi
}

function SetBspwmConf() {
	bspc config border_width "$BSPWM_BORDER"
	bspc config top_padding "$2"
	bspc config bottom_padding "$2"
	bspc config normal_border_color "$2" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$2"
	bspc config right_padding "$2"
	bspc config window_gap "$BSPWM_GAP"
}

function SetRice() {
	
	case $RICETHEME in
		  
		isabel)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 45 "#b8bfe5" "#b8bfe5" "#7560d3" "#81ae5f" 5 5 "$BSPWM_GAP" 
		  
		  killeww
		  launch polybar -q isa-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
	esac		
}

# ReloadTermite

function AutoStartApps() {
	
	launch sxhkd -c ${bspdir}/sxhkdrc
	launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf
	# launch picom --legacy-backends --config ${bspdir}/rices/$RICETHEME/picom.conf
	
	if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
		/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
	fi

	feh --no-fehbg --bg-fill ~/.config/bspwm/rices/$RICETHEME/walls/wallheaven-lain.jpg
	xsetroot -cursor_name left_ptr
	
}
